### ISSUE TITLE
Analytics DAS receivers should accept multiple server names and ports

### ISSUE THREAD

**Issue by chamilad** [wso2/puppet-apim#32]
The following Hieradata only accepts one Thrift Receiver whereas multiple receivers are possible to be added [1].
![image](https://user-images.githubusercontent.com/505989/27170288-013b67ec-51cb-11e7-9d6e-0dc1f4359724.png)

The entries `server_host` and `server_port` should probably change to a list of objects that accepts multiple receivers.

```yaml
wso2::analytics:
  receivers:
    -
      host: host1
      port: port1
    -
      host: host2
      port: port2
```

[1] - https://github.com/wso2/puppet-apim/blob/master/wso2am_runtime/hieradata/dev/wso2/wso2am_runtime/pattern-2/default.yaml#L247-L254
