### ISSUE TITLE
No configured pattern for Traffic Manager in HA

### ISSUE THREAD

**Issue by nu1silva** [wso2/puppet-apim#47]
**Description:**
Could not find a pattern that would enable HA for the traffic manager.

**Suggested Labels:**
Improvement

**Suggested Assignees:**
N/A

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    
Ubuntu 14.04

**Steps to reproduce:**
Could not find a pattern to make the Traffic Manager instance HA. Had to add the following to pattern-3 traffic-manager.yaml to get it to HA.
```
wso2::clustering:
  enabled: true
  domain: tm.am.wso2.domain
  sub_domain: mgt
  local_member_host: "%{::ipaddress}"
  local_member_port: 4000
# WKA membership scheme
  membership_scheme: wka
  wka:
    members:
      -
        hostname: 192.168.48.33
        port: 4000
      -
        hostname: 192.168.48.34
        port: 4000
```

**Related Issues:**
N/A
